#!/usr/bin/env bash
set -euo pipefail

SCRIPT_NAME="ubuntu22-system-setup"
SCRIPT_VERSION="1.4.0"
APPLY=false
CONFIG_FILE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --apply)
      APPLY=true
      shift
      ;;
    --config)
      CONFIG_FILE="${2:-}"
      [[ -z "$CONFIG_FILE" ]] && { echo "ERROR: --config requires a file path"; exit 1; }
      shift 2
      ;;
    -h|--help)
      echo "Usage: sudo bash setup/ubuntu22-system-setup.sh [--apply] [--config /path/to/config.conf]"
      exit 0
      ;;
    *)
      echo "ERROR: Unknown option: $1"
      exit 1
      ;;
  esac
done

RUN_ID="$(date +%Y%m%d-%H%M%S)"
LOG_DIR="/root/system-setup-logs/$RUN_ID"
BACKUP_DIR="/root/system-setup-backups/$RUN_ID"
CONFIG_DIR="/root/system-setup-configs"
GENERATED_CONFIG_FILE="$CONFIG_DIR/$RUN_ID.conf"
SUMMARY_FILE="/root/server-baseline-summary.txt"
VERIFY_SCRIPT="/root/ubuntu22-verify.sh"

SWAP_FILE="/swapfile"
DEFAULT_SWAP_SIZE="20G"
LIMIT_PROFILE="recommended"
LIMIT_VALUE="500000"
NPROC_VALUE="500000"
FILE_MAX="2097152"

SERVER_HOSTNAME=""
SERVER_ROLE="general-vps"
SERVER_LOCATION="unknown"
ADMIN_USER="admin"
SWAP_SIZE=""
SWAP_SIZE_BYTES=""
SSH_KEY_OPTION="2"
ADMIN_PUBLIC_KEY=""
EXTRA_TCP_PORTS=""
EXTRA_UDP_PORTS=""
ALLOW_PASSWORDLESS_SUDO="no"
SET_ADMIN_PASSWORD="yes"
SET_ROOT_PASSWORD="yes"
LOCK_ROOT_PASSWORD="no"
ADMIN_LOCAL_PASSWORD_SELECTED="unknown"
ROOT_PASSWORD_CHANGE_SELECTED="unknown"
CONFIG_LOADED=false
SSH_CHANGED=false

if [[ $EUID -ne 0 ]]; then
  echo "Run as root: sudo bash $0 --apply"
  exit 1
fi

mkdir -p "$LOG_DIR" "$BACKUP_DIR" "$CONFIG_DIR"
exec > >(tee -a "$LOG_DIR/console.log") 2>&1

info() { echo; echo ">>> $*"; }
ok() { echo "OK: $*"; }
change() { echo "CHANGE: $*"; }
warn() { echo "WARNING: $*"; }
fail() { echo "ERROR: $*"; exit 1; }

run() {
  echo "+ $*"
  if $APPLY; then
    eval "$@"
  fi
}

quote_value() {
  printf '%q' "$1"
}

save_config() {
  cat > "$GENERATED_CONFIG_FILE" <<EOF
# Generated by $SCRIPT_NAME v$SCRIPT_VERSION
# Created: $(date -u)
SERVER_HOSTNAME=$(quote_value "$SERVER_HOSTNAME")
SERVER_ROLE=$(quote_value "$SERVER_ROLE")
SERVER_LOCATION=$(quote_value "$SERVER_LOCATION")
ADMIN_USER=$(quote_value "$ADMIN_USER")
SWAP_SIZE=$(quote_value "$SWAP_SIZE")
LIMIT_PROFILE=$(quote_value "$LIMIT_PROFILE")
LIMIT_VALUE=$(quote_value "$LIMIT_VALUE")
NPROC_VALUE=$(quote_value "$NPROC_VALUE")
FILE_MAX=$(quote_value "$FILE_MAX")
SSH_KEY_OPTION=$(quote_value "$SSH_KEY_OPTION")
ADMIN_PUBLIC_KEY=$(quote_value "$ADMIN_PUBLIC_KEY")
EXTRA_TCP_PORTS=$(quote_value "$EXTRA_TCP_PORTS")
EXTRA_UDP_PORTS=$(quote_value "$EXTRA_UDP_PORTS")
ALLOW_PASSWORDLESS_SUDO=$(quote_value "$ALLOW_PASSWORDLESS_SUDO")
SET_ADMIN_PASSWORD=$(quote_value "$SET_ADMIN_PASSWORD")
SET_ROOT_PASSWORD=$(quote_value "$SET_ROOT_PASSWORD")
LOCK_ROOT_PASSWORD=$(quote_value "$LOCK_ROOT_PASSWORD")
EOF
  chmod 600 "$GENERATED_CONFIG_FILE"
  ok "Saved configuration: $GENERATED_CONFIG_FILE"
}

load_config() {
  local file="$1"
  [[ -f "$file" ]] || fail "Config file not found: $file"
  # shellcheck disable=SC1090
  source "$file"
  CONFIG_LOADED=true
  CONFIG_FILE="$file"
  ok "Loaded configuration: $CONFIG_FILE"
}

load_latest_config_if_requested() {
  local latest=""
  latest="$(ls -1t "$CONFIG_DIR"/*.conf 2>/dev/null | head -n1 || true)"
  [[ -z "$latest" ]] && return 0

  echo
  echo "Found previous saved configuration:"
  echo "$latest"
  if prompt_yes_no "Reuse this configuration?" "Y"; then
    load_config "$latest"
  fi
}

show_config_summary() {
  echo
  echo "Configuration Summary"
  echo "---------------------"
  echo "Hostname: $SERVER_HOSTNAME"
  echo "Role: $SERVER_ROLE"
  echo "Provider/location: $SERVER_LOCATION"
  echo "Admin user: $ADMIN_USER"
  echo "Swap size: $SWAP_SIZE"
  echo "Limit profile: $LIMIT_PROFILE"
  echo "nofile: $LIMIT_VALUE"
  echo "nproc: $NPROC_VALUE"
  echo "fs.file-max: $FILE_MAX"
  echo "SSH key option: $SSH_KEY_OPTION"
  echo "Extra TCP ports: ${EXTRA_TCP_PORTS:-none}"
  echo "Extra UDP ports: ${EXTRA_UDP_PORTS:-none}"
  echo "Passwordless sudo: $ALLOW_PASSWORDLESS_SUDO"
  echo "Set admin password: $SET_ADMIN_PASSWORD"
  echo "Set root password: $SET_ROOT_PASSWORD"
  echo "Lock root password: $LOCK_ROOT_PASSWORD"
}

password_prompt() {
  local username="$1"
  local label="$2"
  if $APPLY; then
    echo "Password prompt for $label will run now. Input will not be shown."
    passwd "$username"
  else
    echo "DRY-RUN: Would securely prompt to set/change password for $label during --apply mode."
  fi
}

backup_file() {
  local file="$1"
  if [[ -f "$file" ]]; then
    run "cp -a '$file' '$BACKUP_DIR/'"
  fi
}

write_if_changed() {
  local file="$1"
  local content="$2"
  if [[ -f "$file" ]] && cmp -s "$file" <(printf "%s\n" "$content"); then
    ok "$file already matches desired config"
  else
    change "Updating $file"
    backup_file "$file"
    if $APPLY; then
      mkdir -p "$(dirname "$file")"
      printf "%s\n" "$content" > "$file"
    fi
  fi
}

ensure_package() {
  local pkg="$1"
  if dpkg -s "$pkg" >/dev/null 2>&1; then
    ok "Package installed: $pkg"
  else
    run "apt install -y '$pkg'"
  fi
}

remove_package_if_installed() {
  local pkg="$1"
  if dpkg -s "$pkg" >/dev/null 2>&1; then
    run "apt remove -y '$pkg'"
  else
    ok "Package not installed: $pkg"
  fi
}

ensure_line() {
  local file="$1"
  local line="$2"
  if grep -Fxq "$line" "$file" 2>/dev/null; then
    ok "$line exists in $file"
  else
    change "Adding line to $file: $line"
    backup_file "$file"
    run "echo '$line' >> '$file'"
  fi
}

set_sshd_option() {
  local key="$1"
  local value="$2"
  if grep -Eq "^[#[:space:]]*$key[[:space:]]+" /etc/ssh/sshd_config; then
    if grep -Eq "^$key[[:space:]]+$value$" /etc/ssh/sshd_config; then
      ok "SSH $key $value"
    else
      change "SSH $key $value"
      run "sed -i 's|^[#[:space:]]*$key[[:space:]].*|$key $value|' /etc/ssh/sshd_config"
      SSH_CHANGED=true
    fi
  else
    change "Adding SSH $key $value"
    run "echo '$key $value' >> /etc/ssh/sshd_config"
    SSH_CHANGED=true
  fi
}

prompt_default() {
  local prompt="$1"
  local default="$2"
  local result
  read -rp "$prompt [$default]: " result
  echo "${result:-$default}"
}

prompt_yes_no() {
  local prompt="$1"
  local default="$2"
  local result
  read -rp "$prompt [$default]: " result
  result="${result:-$default}"
  [[ "$result" =~ ^[Yy]$ ]]
}

bool_value() {
  if prompt_yes_no "$1" "$2"; then
    echo "yes"
  else
    echo "no"
  fi
}

validate_number() {
  local value="$1"
  local label="$2"
  [[ "$value" =~ ^[0-9]+$ ]] || fail "$label must be a whole number"
}

recommend_swap_size() {
  local mem_mb
  local role_lc
  mem_mb="$(awk '/MemTotal/ {print int($2/1024)}' /proc/meminfo)"
  role_lc="$(echo "${SERVER_ROLE:-}" | tr '[:upper:]' '[:lower:]')"

  if [[ "$role_lc" =~ blockchain|masternode|node|rpc|docker|build ]]; then
    echo "20G"
  elif (( mem_mb <= 4096 )); then
    echo "4G"
  elif (( mem_mb <= 8192 )); then
    echo "8G"
  elif (( mem_mb <= 32768 )); then
    echo "16G"
  else
    echo "20G"
  fi
}

configure_swap_choice() {
  local recommended
  local choice
  recommended="$(recommend_swap_size)"

  echo
  echo "Swap file size options:"
  echo "1) Auto-recommended based on RAM/server role: $recommended"
  echo "2) Custom size"
  read -rp "Choose option [1-2]: " choice
  choice="${choice:-1}"

  case "$choice" in
    1) SWAP_SIZE="$recommended" ;;
    2) SWAP_SIZE="$(prompt_default 'Custom swap size, examples: 2G, 8G, 20G, 32768M' "$DEFAULT_SWAP_SIZE")" ;;
    *) fail "Invalid swap option" ;;
  esac
}

validate_swap_size() {
  if [[ ! "$SWAP_SIZE" =~ ^[0-9]+[GgMm]$ ]]; then
    fail "Invalid swap size format. Examples: 2G, 8G, 20G, 32768M"
  fi
  SWAP_SIZE_BYTES="$(numfmt --from=iec "$SWAP_SIZE")"
  ok "Selected swap size: $SWAP_SIZE ($SWAP_SIZE_BYTES bytes)"
}

configure_limits_choice() {
  local choice
  echo
  echo "System file/process limit profiles:"
  echo "1) Conservative  - nofile/nproc 65535,   fs.file-max 1048576"
  echo "2) Recommended   - nofile/nproc 500000,  fs.file-max 2097152"
  echo "3) Max           - nofile/nproc 1048576, fs.file-max 4194304"
  echo "4) Custom"
  read -rp "Choose option [1-4]: " choice
  choice="${choice:-2}"

  case "$choice" in
    1)
      LIMIT_PROFILE="conservative"
      LIMIT_VALUE="65535"
      NPROC_VALUE="65535"
      FILE_MAX="1048576"
      ;;
    2)
      LIMIT_PROFILE="recommended"
      LIMIT_VALUE="500000"
      NPROC_VALUE="500000"
      FILE_MAX="2097152"
      ;;
    3)
      LIMIT_PROFILE="max"
      LIMIT_VALUE="1048576"
      NPROC_VALUE="1048576"
      FILE_MAX="4194304"
      ;;
    4)
      LIMIT_PROFILE="custom"
      LIMIT_VALUE="$(prompt_default 'Custom nofile/open files limit' '500000')"
      NPROC_VALUE="$(prompt_default 'Custom nproc/process limit' "$LIMIT_VALUE")"
      FILE_MAX="$(prompt_default 'Custom fs.file-max kernel ceiling' '2097152')"
      ;;
    *) fail "Invalid limits profile option" ;;
  esac
}

validate_limits() {
  validate_number "$LIMIT_VALUE" "nofile limit"
  validate_number "$NPROC_VALUE" "nproc limit"
  validate_number "$FILE_MAX" "fs.file-max"
  ok "Selected limits profile: $LIMIT_PROFILE"
  ok "nofile=$LIMIT_VALUE nproc=$NPROC_VALUE fs.file-max=$FILE_MAX"
}

collect_config() {
  info "Server identity"
  SERVER_HOSTNAME="$(prompt_default 'Server hostname' "$(hostname)")"
  SERVER_ROLE="$(prompt_default 'Server role' "$SERVER_ROLE")"
  SERVER_LOCATION="$(prompt_default 'Provider/location' "$SERVER_LOCATION")"
  ADMIN_USER="$(prompt_default 'Sudo admin username' "$ADMIN_USER")"

  [[ -z "$SERVER_HOSTNAME" ]] && fail "Hostname cannot be empty"
  [[ -z "$ADMIN_USER" ]] && fail "Admin username cannot be empty"

  configure_swap_choice
  configure_limits_choice

  echo
  echo "SSH key setup options for $ADMIN_USER:"
  echo "1) Paste public SSH key"
  echo "2) Copy root's existing authorized_keys"
  echo "3) Generate a new SSH keypair on this server"
  read -rp "Choose option [1-3]: " SSH_KEY_OPTION
  SSH_KEY_OPTION="${SSH_KEY_OPTION:-2}"
  if [[ "$SSH_KEY_OPTION" == "1" ]]; then
    read -rp "Paste the public SSH key for $ADMIN_USER: " ADMIN_PUBLIC_KEY
    [[ -z "$ADMIN_PUBLIC_KEY" ]] && fail "SSH public key cannot be empty"
  fi

  ALLOW_PASSWORDLESS_SUDO="$(bool_value "Allow passwordless sudo for $ADMIN_USER?" "N")"
  SET_ADMIN_PASSWORD="$(bool_value "Set a local password for $ADMIN_USER?" "Y")"
  SET_ROOT_PASSWORD="$(bool_value "Set/change the local root password?" "Y")"
  LOCK_ROOT_PASSWORD="$(bool_value "Lock the root password afterward?" "N")"

  read -rp "Extra TCP ports to allow, comma-separated, blank for none: " EXTRA_TCP_PORTS
  read -rp "Extra UDP ports to allow, comma-separated, blank for none: " EXTRA_UDP_PORTS
}

validate_config() {
  [[ -z "$SERVER_HOSTNAME" ]] && SERVER_HOSTNAME="$(hostname)"
  [[ -z "$ADMIN_USER" ]] && fail "Admin username cannot be empty"
  [[ -z "$SWAP_SIZE" ]] && SWAP_SIZE="$(recommend_swap_size)"
  validate_swap_size
  validate_limits
}

create_verify_script() {
  cat > "$VERIFY_SCRIPT" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

echo "========================================="
echo " Ubuntu 22.04 Setup Verification"
echo "========================================="

check() {
  local name="$1"
  local cmd="$2"
  echo
  echo "---- $name ----"
  eval "$cmd" || echo "FAILED: $name"
}

check "Swap" "swapon --show && free -h && grep '/swapfile' /etc/fstab"
check "Sysctl memory tuning" "sysctl vm.swappiness vm.vfs_cache_pressure vm.dirty_ratio vm.dirty_background_ratio"
check "Sysctl file/network/kernel tuning" "sysctl fs.file-max fs.inotify.max_user_watches fs.inotify.max_user_instances net.core.somaxconn net.ipv4.tcp_max_syn_backlog net.core.default_qdisc net.ipv4.tcp_congestion_control kernel.panic"
check "Limits config file" "cat /etc/security/limits.d/99-custom-limits.conf"
check "PAM limits" "grep pam_limits.so /etc/pam.d/common-session /etc/pam.d/common-session-noninteractive"
check "Systemd limits" "cat /etc/systemd/system.conf.d/99-custom-limits.conf && systemctl show --property DefaultLimitNOFILE --property DefaultLimitNPROC"
check "Current shell limit" "ulimit -n && ulimit -u"
check "Timezone and time sync" "timedatectl"
check "Chrony service" "systemctl is-enabled chrony && systemctl is-active chrony && chronyc tracking && chronyc sources"
check "Old/conflicting time services" "systemctl is-active systemd-timesyncd || true; dpkg -s ntp >/dev/null 2>&1 && echo 'WARNING: ntp package still installed' || echo 'OK: ntp package removed'"
check "UFW firewall" "ufw status verbose"
check "Fail2Ban" "systemctl is-enabled fail2ban && systemctl is-active fail2ban && fail2ban-client status || true"
check "SSH config" "sshd -t && grep -E '^(PermitRootLogin|PasswordAuthentication|PubkeyAuthentication|KbdInteractiveAuthentication|ChallengeResponseAuthentication|UsePAM|MaxAuthTries|ClientAliveInterval|ClientAliveCountMax)' /etc/ssh/sshd_config"
check "fstrim timer" "systemctl is-enabled fstrim.timer && systemctl is-active fstrim.timer && systemctl list-timers fstrim.timer --no-pager"
check "CPU microcode packages" "dpkg -l | awk '/^ii/ && ($2 == \"intel-microcode\" || $2 == \"amd64-microcode\") {print $2, $3}' || true"
check "Installed utility packages" "dpkg -l htop btop iotop iftop nvme-cli smartmontools curl wget unzip jq git net-tools dnsutils tmux rsync lsof fail2ban ufw unattended-upgrades needrestart chrony ntpstat logrotate 2>/dev/null | awk '/^ii/ {print $2, $3}'"
check "Baseline summary" "cat /root/server-baseline-summary.txt 2>/dev/null || echo 'No summary file found'"
check "Saved configs" "ls -lah /root/system-setup-configs/ 2>/dev/null || echo 'No config folder found'"
check "Backup folders" "ls -lah /root/system-setup-backups/ 2>/dev/null || echo 'No backup folder found'"
check "Log folders" "ls -lah /root/system-setup-logs/ 2>/dev/null || echo 'No log folder found'"

echo
echo "========================================="
echo " Verification complete"
echo "========================================="
EOF
  chmod +x "$VERIFY_SCRIPT"
}

write_summary() {
  local ips
  ips="$(hostname -I 2>/dev/null | xargs || true)"
  cat > "$SUMMARY_FILE" <<EOF
Ubuntu Server Baseline Summary
==============================
Script: $SCRIPT_NAME
Version: $SCRIPT_VERSION
Run ID: $RUN_ID
Applied: $APPLY
Config Loaded: $CONFIG_LOADED
Config File: ${CONFIG_FILE:-$GENERATED_CONFIG_FILE}
Date UTC: $(date -u)
Hostname: $(hostname)
Server Role: ${SERVER_ROLE:-unknown}
Provider/Location: ${SERVER_LOCATION:-unknown}
Admin User: ${ADMIN_USER:-unknown}
Admin Local Password Selected: ${ADMIN_LOCAL_PASSWORD_SELECTED:-unknown}
Root Password Change Selected: ${ROOT_PASSWORD_CHANGE_SELECTED:-unknown}
Desired Swap Size: ${SWAP_SIZE:-unknown}
Limit Profile: ${LIMIT_PROFILE:-unknown}
nofile Limit: ${LIMIT_VALUE:-unknown}
nproc Limit: ${NPROC_VALUE:-unknown}
fs.file-max: ${FILE_MAX:-unknown}
IP Addresses: $ips

Swap:
$(swapon --show 2>/dev/null || true)

Memory:
$(free -h 2>/dev/null || true)

UFW:
$(ufw status verbose 2>/dev/null || true)

Fail2Ban:
$(systemctl is-active fail2ban 2>/dev/null || true)

Chrony:
$(chronyc tracking 2>/dev/null || true)

SSH Key Settings:
$(grep -E '^(PermitRootLogin|PasswordAuthentication|PubkeyAuthentication|KbdInteractiveAuthentication|ChallengeResponseAuthentication|UsePAM|MaxAuthTries|ClientAliveInterval|ClientAliveCountMax)' /etc/ssh/sshd_config 2>/dev/null || true)

Sysctl:
$(sysctl vm.swappiness vm.vfs_cache_pressure fs.file-max net.ipv4.tcp_congestion_control kernel.panic 2>/dev/null || true)

Microcode Packages:
$(dpkg -l 2>/dev/null | awk '/^ii/ && ($2 == "intel-microcode" || $2 == "amd64-microcode") {print $2, $3}' || true)

Logs: $LOG_DIR
Backups: $BACKUP_DIR
Saved Config: ${CONFIG_FILE:-$GENERATED_CONFIG_FILE}
Verify Script: $VERIFY_SCRIPT
EOF
}

echo "========================================="
echo " $SCRIPT_NAME v$SCRIPT_VERSION"
echo " Mode: $([[ "$APPLY" == true ]] && echo APPLY || echo DRY-RUN)"
echo "========================================="

if [[ -n "$CONFIG_FILE" ]]; then
  load_config "$CONFIG_FILE"
elif $APPLY; then
  load_latest_config_if_requested
fi

if ! $CONFIG_LOADED; then
  if ! $APPLY; then
    warn "Dry-run mode will NOT ask for hidden password entry. Password prompts only run with --apply."
  fi
  collect_config
  save_config
else
  show_config_summary
  if ! prompt_yes_no "Continue with this loaded configuration?" "Y"; then
    fail "Aborted by user"
  fi
fi

validate_config
show_config_summary

if [[ "$(hostname)" != "$SERVER_HOSTNAME" ]]; then
  run "hostnamectl set-hostname '$SERVER_HOSTNAME'"
else
  ok "Hostname already $SERVER_HOSTNAME"
fi

info "Updating package index"
run "apt update -y"

info "Installing baseline packages"
PACKAGES=(
  htop btop iotop iftop nvme-cli smartmontools curl wget unzip jq git
  net-tools dnsutils tmux rsync lsof fail2ban ufw unattended-upgrades
  needrestart chrony ntpstat logrotate sudo openssh-server
)
for pkg in "${PACKAGES[@]}"; do ensure_package "$pkg"; done

if dpkg -s ntp >/dev/null 2>&1; then
  run "apt remove -y ntp"
else
  ok "ntp package not installed"
fi

info "Configuring timezone"
if [[ "$(timedatectl show -p Timezone --value || true)" != "UTC" ]]; then
  run "timedatectl set-timezone UTC"
else
  ok "Timezone already UTC"
fi

info "Creating sudo admin user"
if id "$ADMIN_USER" >/dev/null 2>&1; then
  ok "User $ADMIN_USER already exists"
else
  run "adduser --disabled-password --gecos '' '$ADMIN_USER'"
fi
run "usermod -aG sudo '$ADMIN_USER'"

ADMIN_HOME="/home/$ADMIN_USER"
ADMIN_SSH_DIR="$ADMIN_HOME/.ssh"
ADMIN_AUTH_KEYS="$ADMIN_SSH_DIR/authorized_keys"

run "mkdir -p '$ADMIN_SSH_DIR'"
run "touch '$ADMIN_AUTH_KEYS'"
run "chmod 700 '$ADMIN_SSH_DIR'"
run "chmod 600 '$ADMIN_AUTH_KEYS'"
run "chown -R '$ADMIN_USER:$ADMIN_USER' '$ADMIN_SSH_DIR'"

case "$SSH_KEY_OPTION" in
  1)
    [[ -z "$ADMIN_PUBLIC_KEY" ]] && fail "SSH_KEY_OPTION=1 requires ADMIN_PUBLIC_KEY in config"
    if grep -Fxq "$ADMIN_PUBLIC_KEY" "$ADMIN_AUTH_KEYS" 2>/dev/null; then
      ok "SSH key already exists for $ADMIN_USER"
    else
      run "echo '$ADMIN_PUBLIC_KEY' >> '$ADMIN_AUTH_KEYS'"
    fi
    ;;
  2)
    if [[ -f /root/.ssh/authorized_keys ]]; then
      run "cat /root/.ssh/authorized_keys >> '$ADMIN_AUTH_KEYS'"
      run "sort -u '$ADMIN_AUTH_KEYS' -o '$ADMIN_AUTH_KEYS'"
    else
      fail "/root/.ssh/authorized_keys not found. Use SSH_KEY_OPTION=1 or 3."
    fi
    ;;
  3)
    KEY_PATH="/root/${ADMIN_USER}_ed25519"
    if [[ -f "$KEY_PATH" ]]; then
      ok "Generated key already exists at $KEY_PATH"
    else
      run "ssh-keygen -t ed25519 -a 100 -f '$KEY_PATH' -N '' -C '${ADMIN_USER}@${SERVER_HOSTNAME}'"
      run "cat '${KEY_PATH}.pub' >> '$ADMIN_AUTH_KEYS'"
    fi
    warn "Save private key securely from: $KEY_PATH"
    echo "Connect with: ssh -i ${ADMIN_USER}_ed25519 $ADMIN_USER@SERVER_IP"
    ;;
  *) fail "Invalid SSH key option: $SSH_KEY_OPTION" ;;
esac

run "chown -R '$ADMIN_USER:$ADMIN_USER' '$ADMIN_SSH_DIR'"
run "chmod 700 '$ADMIN_SSH_DIR'"
run "chmod 600 '$ADMIN_AUTH_KEYS'"

if $APPLY && [[ ! -s "$ADMIN_AUTH_KEYS" ]]; then
  fail "$ADMIN_USER has no SSH authorized_keys. Refusing to disable root SSH."
fi

if [[ "$ALLOW_PASSWORDLESS_SUDO" == "yes" ]]; then
  run "echo '$ADMIN_USER ALL=(ALL) NOPASSWD:ALL' > '/etc/sudoers.d/90-$ADMIN_USER'"
  run "chmod 440 '/etc/sudoers.d/90-$ADMIN_USER'"
else
  ok "Normal sudo selected. A local password is recommended for sudo prompts."
fi

if [[ "$SET_ADMIN_PASSWORD" == "yes" ]]; then
  ADMIN_LOCAL_PASSWORD_SELECTED="yes"
  password_prompt "$ADMIN_USER" "$ADMIN_USER"
else
  ADMIN_LOCAL_PASSWORD_SELECTED="no"
  warn "No local password selected for $ADMIN_USER. SSH key login can still work, but console/sudo recovery may be limited."
fi

$APPLY && visudo -cf /etc/sudoers

info "Root account security"
if [[ "$SET_ROOT_PASSWORD" == "yes" ]]; then
  ROOT_PASSWORD_CHANGE_SELECTED="yes"
  password_prompt root root
else
  ROOT_PASSWORD_CHANGE_SELECTED="no"
fi
if [[ "$LOCK_ROOT_PASSWORD" == "yes" ]]; then
  run "passwd -l root"
else
  ok "Root password left enabled for console/recovery use"
fi

info "Checking swap"
CURRENT_SWAP_SIZE="0"
if swapon --show=NAME,SIZE --bytes --noheadings | awk '{print $1}' | grep -qx "$SWAP_FILE"; then
  CURRENT_SWAP_SIZE="$(swapon --show=NAME,SIZE --bytes --noheadings | awk -v s="$SWAP_FILE" '$1==s {print $2}')"
fi
if [[ "$CURRENT_SWAP_SIZE" == "$SWAP_SIZE_BYTES" ]] && grep -q "^$SWAP_FILE none swap sw 0 0" /etc/fstab; then
  ok "$SWAP_SIZE swap already active and persistent"
else
  change "Configuring $SWAP_SIZE swap"
  backup_file /etc/fstab
  run "swapoff '$SWAP_FILE' || true"
  run "rm -f '$SWAP_FILE'"
  run "sed -i '\|$SWAP_FILE|d' /etc/fstab"
  run "fallocate -l '$SWAP_SIZE' '$SWAP_FILE'"
  run "chmod 600 '$SWAP_FILE'"
  run "mkswap '$SWAP_FILE'"
  run "swapon '$SWAP_FILE'"
  run "echo '$SWAP_FILE none swap sw 0 0' >> /etc/fstab"
fi

info "Applying sysctl tuning"
SYSCTL_CONTENT="vm.swappiness=10
vm.vfs_cache_pressure=50
vm.dirty_ratio=15
vm.dirty_background_ratio=5
fs.file-max=$FILE_MAX
fs.inotify.max_user_watches=1048576
fs.inotify.max_user_instances=8192
net.core.somaxconn=65535
net.ipv4.tcp_max_syn_backlog=8192
net.core.default_qdisc=fq
net.ipv4.tcp_congestion_control=bbr
kernel.panic=10"
write_if_changed /etc/sysctl.d/99-custom-system-tuning.conf "$SYSCTL_CONTENT"
run "sysctl --system"

info "Applying security and systemd limits"
LIMITS_CONTENT="* soft nofile $LIMIT_VALUE
* hard nofile $LIMIT_VALUE
* soft nproc $NPROC_VALUE
* hard nproc $NPROC_VALUE
root soft nofile $LIMIT_VALUE
root hard nofile $LIMIT_VALUE
root soft nproc $NPROC_VALUE
root hard nproc $NPROC_VALUE"
write_if_changed /etc/security/limits.d/99-custom-limits.conf "$LIMITS_CONTENT"
ensure_line /etc/pam.d/common-session "session required pam_limits.so"
ensure_line /etc/pam.d/common-session-noninteractive "session required pam_limits.so"
SYSTEMD_LIMITS_CONTENT="[Manager]
DefaultLimitNOFILE=$LIMIT_VALUE
DefaultLimitNPROC=$NPROC_VALUE"
write_if_changed /etc/systemd/system.conf.d/99-custom-limits.conf "$SYSTEMD_LIMITS_CONTENT"
run "systemctl daemon-reexec"

info "Configuring UFW firewall"
if ufw status | grep -q "22/tcp"; then
  ok "UFW already allows SSH port 22"
else
  run "ufw allow 22/tcp comment 'SSH'"
fi
IFS=',' read -ra TCP_PORTS <<< "$EXTRA_TCP_PORTS"
for port in "${TCP_PORTS[@]}"; do
  port="$(echo "$port" | xargs)"
  [[ -n "$port" ]] && run "ufw allow ${port}/tcp"
done
IFS=',' read -ra UDP_PORTS <<< "$EXTRA_UDP_PORTS"
for port in "${UDP_PORTS[@]}"; do
  port="$(echo "$port" | xargs)"
  [[ -n "$port" ]] && run "ufw allow ${port}/udp"
done
if ufw status | grep -q "Status: active"; then
  ok "UFW already active"
else
  run "ufw --force enable"
fi

info "Configuring Fail2Ban"
run "systemctl enable fail2ban"
if systemctl is-active fail2ban >/dev/null 2>&1; then
  ok "fail2ban already active"
else
  run "systemctl start fail2ban"
fi

info "Configuring Chrony"
CHRONY_CONTENT="pool 0.ca.pool.ntp.org iburst maxsources 4
pool 1.ca.pool.ntp.org iburst maxsources 4
pool 2.ca.pool.ntp.org iburst maxsources 4
pool 3.ca.pool.ntp.org iburst maxsources 4
pool 0.north-america.pool.ntp.org iburst maxsources 4
pool 1.north-america.pool.ntp.org iburst maxsources 4
pool 2.north-america.pool.ntp.org iburst maxsources 4
pool 3.north-america.pool.ntp.org iburst maxsources 4
pool ntp.ubuntu.com iburst maxsources 4
pool pool.ntp.org iburst maxsources 4
driftfile /var/lib/chrony/chrony.drift
makestep 1.0 3
rtcsync
logdir /var/log/chrony"
write_if_changed /etc/chrony/chrony.conf "$CHRONY_CONTENT"
run "systemctl disable --now systemd-timesyncd || true"
run "systemctl enable chrony"
run "systemctl restart chrony"

info "Hardening SSH"
backup_file /etc/ssh/sshd_config
set_sshd_option PermitRootLogin no
set_sshd_option PasswordAuthentication no
set_sshd_option PubkeyAuthentication yes
set_sshd_option KbdInteractiveAuthentication no
set_sshd_option ChallengeResponseAuthentication no
set_sshd_option UsePAM yes
set_sshd_option MaxAuthTries 3
set_sshd_option ClientAliveInterval 300
set_sshd_option ClientAliveCountMax 2
$APPLY && sshd -t
[[ "$SSH_CHANGED" == true ]] && run "systemctl restart ssh"

info "Enabling SSD/NVMe trim timer"
systemctl is-enabled fstrim.timer >/dev/null 2>&1 || run "systemctl enable fstrim.timer"
systemctl is-active fstrim.timer >/dev/null 2>&1 || run "systemctl start fstrim.timer"

info "Installing correct CPU microcode package"
CPU_VENDOR="$(grep -m1 'vendor_id' /proc/cpuinfo | awk '{print $3}' || true)"
case "$CPU_VENDOR" in
  GenuineIntel)
    remove_package_if_installed amd64-microcode
    ensure_package intel-microcode
    ;;
  AuthenticAMD)
    remove_package_if_installed intel-microcode
    ensure_package amd64-microcode
    ;;
  *)
    warn "Unknown CPU vendor '$CPU_VENDOR'. Skipping microcode package cleanup."
    ;;
esac

info "Creating verification script"
if $APPLY; then
  create_verify_script
  write_summary
else
  echo "Dry-run: would create $VERIFY_SCRIPT and $SUMMARY_FILE"
fi

echo
echo "========================================="
echo " FINAL STATUS"
echo "========================================="
swapon --show || true
free -h || true
sysctl vm.swappiness vm.vfs_cache_pressure fs.file-max net.ipv4.tcp_congestion_control kernel.panic || true
ufw status verbose || true
systemctl status fail2ban --no-pager || true
chronyc tracking || true
timedatectl || true
sshd -t && echo "SSHD config valid"
echo "Logs: $LOG_DIR"
echo "Backups: $BACKUP_DIR"
echo "Saved config: ${CONFIG_FILE:-$GENERATED_CONFIG_FILE}"
echo "Summary: $SUMMARY_FILE"
echo "Verify script: $VERIFY_SCRIPT"

echo
echo "IMPORTANT: Before closing your current SSH/session, open a NEW terminal and test:"
echo "ssh $ADMIN_USER@SERVER_IP"
echo "sudo whoami"
echo "Expected result: root"

if prompt_yes_no "Reboot now?" "N"; then
  run "reboot"
else
  echo "Recommended: reboot after first successful apply."
fi
