#!/usr/bin/env bash
set -euo pipefail

SCRIPT_NAME="ubuntu22-system-setup"
SCRIPT_VERSION="1.6.0"
APPLY=false
CONFIG_FILE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --apply) APPLY=true; shift ;;
    --config)
      CONFIG_FILE="${2:-}"
      [[ -z "$CONFIG_FILE" ]] && { echo "ERROR: --config requires a file path"; exit 1; }
      shift 2
      ;;
    -h|--help)
      echo "Usage: sudo bash setup/ubuntu22-system-setup.sh [--apply] [--config /path/to/config.conf]"
      exit 0
      ;;
    *) echo "ERROR: Unknown option: $1"; exit 1 ;;
  esac
done

RUN_ID="$(date +%Y%m%d-%H%M%S)"
LOG_DIR="/root/system-setup-logs/$RUN_ID"
BACKUP_DIR="/root/system-setup-backups/$RUN_ID"
CONFIG_DIR="/root/system-setup-configs"
GENERATED_CONFIG_FILE="$CONFIG_DIR/$RUN_ID.conf"
SUMMARY_FILE="/root/server-baseline-summary.txt"
VERIFY_SCRIPT="/root/ubuntu22-verify.sh"

SWAP_FILE="/swapfile"
DEFAULT_SWAP_SIZE="20G"
LIMIT_PROFILE="recommended"
LIMIT_VALUE="500000"
NPROC_VALUE="500000"
FILE_MAX="2097152"
SERVER_HOSTNAME=""
SERVER_ROLE="general-vps"
SERVER_LOCATION="unknown"
ADMIN_USER="admin"
SWAP_SIZE=""
SWAP_SIZE_BYTES=""
SSH_KEY_OPTION="2"
ADMIN_PUBLIC_KEY=""
EXTRA_TCP_PORTS=""
EXTRA_UDP_PORTS=""
ALLOW_PASSWORDLESS_SUDO="no"
SET_ADMIN_PASSWORD="yes"
SET_ROOT_PASSWORD="yes"
LOCK_ROOT_PASSWORD="no"
RUN_SYSTEM_UPDATES="yes"
ENABLE_UNATTENDED_SECURITY_UPDATES="yes"
ENABLE_WIREGUARD="no"
WIREGUARD_MODE="install-only"
WIREGUARD_INTERFACE="wg0"
WIREGUARD_PORT="51820"
WIREGUARD_ADDRESS="10.100.0.1/24"
WIREGUARD_PEER_PUBLIC_KEY=""
WIREGUARD_PEER_ALLOWED_IPS=""
CONFIG_LOADED=false
SSH_CHANGED=false
ADMIN_LOCAL_PASSWORD_SELECTED="unknown"
ROOT_PASSWORD_CHANGE_SELECTED="unknown"

[[ $EUID -ne 0 ]] && { echo "Run as root: sudo bash $0 --apply"; exit 1; }
mkdir -p "$LOG_DIR" "$BACKUP_DIR" "$CONFIG_DIR"
exec > >(tee -a "$LOG_DIR/console.log") 2>&1

info(){ echo; echo ">>> $*"; }
ok(){ echo "OK: $*"; }
change(){ echo "CHANGE: $*"; }
warn(){ echo "WARNING: $*"; }
fail(){ echo "ERROR: $*"; exit 1; }
run(){ echo "+ $*"; $APPLY && eval "$@"; }
quote_value(){ printf '%q' "$1"; }

backup_file(){ local f="$1"; [[ -f "$f" ]] && run "cp -a '$f' '$BACKUP_DIR/'"; }
write_if_changed(){
  local f="$1" c="$2"
  if [[ -f "$f" ]] && cmp -s "$f" <(printf "%s\n" "$c"); then ok "$f already matches desired config"
  else
    change "Updating $f"; backup_file "$f"
    if $APPLY; then mkdir -p "$(dirname "$f")"; printf "%s\n" "$c" > "$f"; fi
  fi
}
ensure_package(){ local p="$1"; dpkg -s "$p" >/dev/null 2>&1 && ok "Package installed: $p" || run "apt install -y '$p'"; }
ensure_line(){
  local f="$1" l="$2"
  if grep -Fxq "$l" "$f" 2>/dev/null; then ok "$l exists in $f"
  else change "Adding line to $f: $l"; backup_file "$f"; run "echo '$l' >> '$f'"; fi
}
prompt_default(){ local p="$1" d="$2" r; read -rp "$p [$d]: " r; echo "${r:-$d}"; }
prompt_yes_no(){ local p="$1" d="$2" r; read -rp "$p [$d]: " r; r="${r:-$d}"; [[ "$r" =~ ^[Yy]$ ]]; }
bool_value(){ prompt_yes_no "$1" "$2" && echo yes || echo no; }
validate_number(){ [[ "$1" =~ ^[0-9]+$ ]] || fail "$2 must be a whole number"; }

save_config(){
  cat > "$GENERATED_CONFIG_FILE" <<EOF
# Generated by $SCRIPT_NAME v$SCRIPT_VERSION
# Created: $(date -u)
SERVER_HOSTNAME=$(quote_value "$SERVER_HOSTNAME")
SERVER_ROLE=$(quote_value "$SERVER_ROLE")
SERVER_LOCATION=$(quote_value "$SERVER_LOCATION")
ADMIN_USER=$(quote_value "$ADMIN_USER")
SWAP_SIZE=$(quote_value "$SWAP_SIZE")
LIMIT_PROFILE=$(quote_value "$LIMIT_PROFILE")
LIMIT_VALUE=$(quote_value "$LIMIT_VALUE")
NPROC_VALUE=$(quote_value "$NPROC_VALUE")
FILE_MAX=$(quote_value "$FILE_MAX")
SSH_KEY_OPTION=$(quote_value "$SSH_KEY_OPTION")
ADMIN_PUBLIC_KEY=$(quote_value "$ADMIN_PUBLIC_KEY")
EXTRA_TCP_PORTS=$(quote_value "$EXTRA_TCP_PORTS")
EXTRA_UDP_PORTS=$(quote_value "$EXTRA_UDP_PORTS")
ALLOW_PASSWORDLESS_SUDO=$(quote_value "$ALLOW_PASSWORDLESS_SUDO")
SET_ADMIN_PASSWORD=$(quote_value "$SET_ADMIN_PASSWORD")
SET_ROOT_PASSWORD=$(quote_value "$SET_ROOT_PASSWORD")
LOCK_ROOT_PASSWORD=$(quote_value "$LOCK_ROOT_PASSWORD")
RUN_SYSTEM_UPDATES=$(quote_value "$RUN_SYSTEM_UPDATES")
ENABLE_UNATTENDED_SECURITY_UPDATES=$(quote_value "$ENABLE_UNATTENDED_SECURITY_UPDATES")
ENABLE_WIREGUARD=$(quote_value "$ENABLE_WIREGUARD")
WIREGUARD_MODE=$(quote_value "$WIREGUARD_MODE")
WIREGUARD_INTERFACE=$(quote_value "$WIREGUARD_INTERFACE")
WIREGUARD_PORT=$(quote_value "$WIREGUARD_PORT")
WIREGUARD_ADDRESS=$(quote_value "$WIREGUARD_ADDRESS")
WIREGUARD_PEER_PUBLIC_KEY=$(quote_value "$WIREGUARD_PEER_PUBLIC_KEY")
WIREGUARD_PEER_ALLOWED_IPS=$(quote_value "$WIREGUARD_PEER_ALLOWED_IPS")
EOF
  chmod 600 "$GENERATED_CONFIG_FILE"
  ok "Saved configuration: $GENERATED_CONFIG_FILE"
}
load_config(){ local f="$1"; [[ -f "$f" ]] || fail "Config file not found: $f"; source "$f"; CONFIG_LOADED=true; CONFIG_FILE="$f"; ok "Loaded configuration: $CONFIG_FILE"; }
load_latest_config_if_requested(){ local latest; latest="$(ls -1t "$CONFIG_DIR"/*.conf 2>/dev/null | head -n1 || true)"; [[ -z "$latest" ]] && return 0; echo; echo "Found previous saved configuration:"; echo "$latest"; prompt_yes_no "Reuse this configuration?" "Y" && load_config "$latest"; }

show_config_summary(){
  echo; echo "Configuration Summary"; echo "---------------------"
  echo "Hostname: $SERVER_HOSTNAME"
  echo "Role: $SERVER_ROLE"
  echo "Provider/location: $SERVER_LOCATION"
  echo "Admin user: $ADMIN_USER"
  echo "Swap size: $SWAP_SIZE"
  echo "Limit profile: $LIMIT_PROFILE"
  echo "nofile: $LIMIT_VALUE"
  echo "nproc: $NPROC_VALUE"
  echo "fs.file-max: $FILE_MAX"
  echo "SSH key option: $SSH_KEY_OPTION"
  echo "Extra TCP ports: ${EXTRA_TCP_PORTS:-none}"
  echo "Extra UDP ports: ${EXTRA_UDP_PORTS:-none}"
  echo "Passwordless sudo: $ALLOW_PASSWORDLESS_SUDO"
  echo "Set admin password: $SET_ADMIN_PASSWORD"
  echo "Set root password: $SET_ROOT_PASSWORD"
  echo "Lock root password: $LOCK_ROOT_PASSWORD"
  echo "Run system updates: $RUN_SYSTEM_UPDATES"
  echo "Enable unattended security updates: $ENABLE_UNATTENDED_SECURITY_UPDATES"
  echo "Enable WireGuard: $ENABLE_WIREGUARD"
  [[ "$ENABLE_WIREGUARD" == yes ]] && echo "WireGuard mode/interface/port/address: $WIREGUARD_MODE / $WIREGUARD_INTERFACE / $WIREGUARD_PORT / $WIREGUARD_ADDRESS"
}

recommend_swap_size(){
  local mem_mb role_lc
  mem_mb="$(awk '/MemTotal/ {print int($2/1024)}' /proc/meminfo)"
  role_lc="$(echo "${SERVER_ROLE:-}" | tr '[:upper:]' '[:lower:]')"
  if [[ "$role_lc" =~ blockchain|masternode|node|rpc|docker|build ]]; then echo 20G
  elif (( mem_mb <= 4096 )); then echo 4G
  elif (( mem_mb <= 8192 )); then echo 8G
  elif (( mem_mb <= 32768 )); then echo 16G
  else echo 20G; fi
}
configure_swap_choice(){
  local recommended choice
  recommended="$(recommend_swap_size)"
  echo; echo "Swap file size options:"; echo "1) Auto-recommended based on RAM/server role: $recommended"; echo "2) Custom size"
  read -rp "Choose option [1-2]: " choice; choice="${choice:-1}"
  case "$choice" in 1) SWAP_SIZE="$recommended";; 2) SWAP_SIZE="$(prompt_default 'Custom swap size, examples: 2G, 8G, 20G, 32768M' "$DEFAULT_SWAP_SIZE")";; *) fail "Invalid swap option";; esac
}
validate_swap_size(){ [[ "$SWAP_SIZE" =~ ^[0-9]+[GgMm]$ ]] || fail "Invalid swap size format. Examples: 2G, 8G, 20G, 32768M"; SWAP_SIZE_BYTES="$(numfmt --from=iec "$SWAP_SIZE")"; ok "Selected swap size: $SWAP_SIZE ($SWAP_SIZE_BYTES bytes)"; }

configure_limits_choice(){
  local choice
  echo; echo "System file/process limit profiles:"
  echo "1) Conservative  - nofile/nproc 65535,   fs.file-max 1048576"
  echo "2) Recommended   - nofile/nproc 500000,  fs.file-max 2097152"
  echo "3) Max           - nofile/nproc 1048576, fs.file-max 4194304"
  echo "4) Custom"
  read -rp "Choose option [1-4]: " choice; choice="${choice:-2}"
  case "$choice" in
    1) LIMIT_PROFILE=conservative; LIMIT_VALUE=65535; NPROC_VALUE=65535; FILE_MAX=1048576;;
    2) LIMIT_PROFILE=recommended; LIMIT_VALUE=500000; NPROC_VALUE=500000; FILE_MAX=2097152;;
    3) LIMIT_PROFILE=max; LIMIT_VALUE=1048576; NPROC_VALUE=1048576; FILE_MAX=4194304;;
    4) LIMIT_PROFILE=custom; LIMIT_VALUE="$(prompt_default 'Custom nofile/open files limit' '500000')"; NPROC_VALUE="$(prompt_default 'Custom nproc/process limit' "$LIMIT_VALUE")"; FILE_MAX="$(prompt_default 'Custom fs.file-max kernel ceiling' '2097152')";;
    *) fail "Invalid limits profile option";;
  esac
}
validate_limits(){ validate_number "$LIMIT_VALUE" "nofile limit"; validate_number "$NPROC_VALUE" "nproc limit"; validate_number "$FILE_MAX" "fs.file-max"; ok "Selected limits profile: $LIMIT_PROFILE"; ok "nofile=$LIMIT_VALUE nproc=$NPROC_VALUE fs.file-max=$FILE_MAX"; }

configure_wireguard_choice(){
  echo
  ENABLE_WIREGUARD="$(bool_value "Install WireGuard VPN support?" "N")"
  [[ "$ENABLE_WIREGUARD" != yes ]] && return 0
  echo "WireGuard options:"
  echo "1) Install package only"
  echo "2) Install + create simple server config"
  read -rp "Choose option [1-2]: " wg_choice
  wg_choice="${wg_choice:-1}"
  case "$wg_choice" in
    1) WIREGUARD_MODE="install-only" ;;
    2) WIREGUARD_MODE="server" ;;
    *) fail "Invalid WireGuard option" ;;
  esac
  WIREGUARD_INTERFACE="$(prompt_default 'WireGuard interface' "$WIREGUARD_INTERFACE")"
  WIREGUARD_PORT="$(prompt_default 'WireGuard UDP port' "$WIREGUARD_PORT")"
  if [[ "$WIREGUARD_MODE" == server ]]; then
    WIREGUARD_ADDRESS="$(prompt_default 'WireGuard server VPN address/CIDR' "$WIREGUARD_ADDRESS")"
    if prompt_yes_no "Add one initial WireGuard peer public key now?" "N"; then
      read -rp "Peer public key: " WIREGUARD_PEER_PUBLIC_KEY
      WIREGUARD_PEER_ALLOWED_IPS="$(prompt_default 'Peer allowed IPs, example 10.100.0.2/32' '10.100.0.2/32')"
    fi
  fi
}
validate_wireguard(){
  [[ "$ENABLE_WIREGUARD" != yes ]] && return 0
  [[ "$WIREGUARD_INTERFACE" =~ ^[a-zA-Z0-9_.-]+$ ]] || fail "Invalid WireGuard interface name"
  validate_number "$WIREGUARD_PORT" "WireGuard port"
  if (( WIREGUARD_PORT < 1 || WIREGUARD_PORT > 65535 )); then fail "WireGuard port must be between 1 and 65535"; fi
  [[ "$WIREGUARD_MODE" == install-only || "$WIREGUARD_MODE" == server ]] || fail "Invalid WireGuard mode"
}

collect_config(){
  info "Server identity"
  SERVER_HOSTNAME="$(prompt_default 'Server hostname' "$(hostname)")"
  SERVER_ROLE="$(prompt_default 'Server role' "$SERVER_ROLE")"
  SERVER_LOCATION="$(prompt_default 'Provider/location' "$SERVER_LOCATION")"
  ADMIN_USER="$(prompt_default 'Sudo admin username' "$ADMIN_USER")"
  [[ -z "$SERVER_HOSTNAME" ]] && fail "Hostname cannot be empty"
  [[ -z "$ADMIN_USER" ]] && fail "Admin username cannot be empty"
  configure_swap_choice; configure_limits_choice
  echo; echo "SSH key setup options for $ADMIN_USER:"; echo "1) Paste public SSH key"; echo "2) Copy root's existing authorized_keys"; echo "3) Generate a new SSH keypair on this server"
  read -rp "Choose option [1-3]: " SSH_KEY_OPTION; SSH_KEY_OPTION="${SSH_KEY_OPTION:-2}"
  if [[ "$SSH_KEY_OPTION" == "1" ]]; then read -rp "Paste the public SSH key for $ADMIN_USER: " ADMIN_PUBLIC_KEY; [[ -z "$ADMIN_PUBLIC_KEY" ]] && fail "SSH public key cannot be empty"; fi
  ALLOW_PASSWORDLESS_SUDO="$(bool_value "Allow passwordless sudo for $ADMIN_USER?" "N")"
  SET_ADMIN_PASSWORD="$(bool_value "Set a local password for $ADMIN_USER?" "Y")"
  SET_ROOT_PASSWORD="$(bool_value "Set/change the local root password?" "Y")"
  LOCK_ROOT_PASSWORD="$(bool_value "Lock the root password afterward?" "N")"
  RUN_SYSTEM_UPDATES="$(bool_value "Run safe Ubuntu 22.04 package updates/patches?" "Y")"
  ENABLE_UNATTENDED_SECURITY_UPDATES="$(bool_value "Enable unattended security updates?" "Y")"
  configure_wireguard_choice
  read -rp "Extra TCP ports to allow, comma-separated, blank for none: " EXTRA_TCP_PORTS
  read -rp "Extra UDP ports to allow, comma-separated, blank for none: " EXTRA_UDP_PORTS
}
validate_config(){ [[ -z "$SERVER_HOSTNAME" ]] && SERVER_HOSTNAME="$(hostname)"; [[ -z "$ADMIN_USER" ]] && fail "Admin username cannot be empty"; [[ -z "$SWAP_SIZE" ]] && SWAP_SIZE="$(recommend_swap_size)"; validate_swap_size; validate_limits; validate_wireguard; }

password_prompt(){ local u="$1" label="$2"; if $APPLY; then echo "Password prompt for $label will run now. Input will not be shown."; passwd "$u"; else echo "DRY-RUN: Would securely prompt to set/change password for $label during --apply mode."; fi; }
set_sshd_option(){ local k="$1" v="$2"; if grep -Eq "^[#[:space:]]*$k[[:space:]]+" /etc/ssh/sshd_config; then if grep -Eq "^$k[[:space:]]+$v$" /etc/ssh/sshd_config; then ok "SSH $k $v"; else change "SSH $k $v"; run "sed -i 's|^[#[:space:]]*$k[[:space:]].*|$k $v|' /etc/ssh/sshd_config"; SSH_CHANGED=true; fi; else change "Adding SSH $k $v"; run "echo '$k $v' >> /etc/ssh/sshd_config"; SSH_CHANGED=true; fi; }

configure_release_upgrades(){
  info "Blocking Ubuntu release upgrades while allowing Ubuntu 22.04 updates"
  if [[ -f /etc/update-manager/release-upgrades ]]; then backup_file /etc/update-manager/release-upgrades; grep -q '^Prompt=' /etc/update-manager/release-upgrades && run "sed -i 's/^Prompt=.*/Prompt=never/' /etc/update-manager/release-upgrades" || run "echo 'Prompt=never' >> /etc/update-manager/release-upgrades"
  else run "mkdir -p /etc/update-manager"; run "printf '%s\n' '[DEFAULT]' 'Prompt=never' > /etc/update-manager/release-upgrades"; fi
}
configure_unattended_upgrades(){
  info "Configuring unattended security updates"
  ensure_package unattended-upgrades; ensure_package apt-listchanges
  write_if_changed /etc/apt/apt.conf.d/20auto-upgrades 'APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
APT::Periodic::AutocleanInterval "7";'
  write_if_changed /etc/apt/apt.conf.d/51baseline-security-upgrades 'Unattended-Upgrade::Allowed-Origins {
        "${distro_id}:${distro_codename}-security";
        "${distro_id}ESMApps:${distro_codename}-apps-security";
        "${distro_id}ESM:${distro_codename}-infra-security";
};
Unattended-Upgrade::Remove-Unused-Dependencies "true";
Unattended-Upgrade::Automatic-Reboot "false";'
  run "systemctl enable unattended-upgrades || true"; run "systemctl restart unattended-upgrades || true"
}
run_system_updates(){ configure_release_upgrades; if [[ "$RUN_SYSTEM_UPDATES" == yes ]]; then info "Running safe Ubuntu 22.04 updates and patches"; run "apt update -y"; run "DEBIAN_FRONTEND=noninteractive apt upgrade -y"; run "DEBIAN_FRONTEND=noninteractive apt full-upgrade -y"; run "apt autoremove -y"; run "apt autoclean -y"; else info "Skipping package updates by config"; run "apt update -y"; fi; [[ "$ENABLE_UNATTENDED_SECURITY_UPDATES" == yes ]] && configure_unattended_upgrades || ok "Unattended security updates not enabled by config"; }

microcode_report(){ dpkg-query -W -f='${binary:Package} ${Version}\n' intel-microcode amd64-microcode 2>/dev/null || true; }
configure_microcode(){
  info "Installing correct CPU microcode package"
  local vendor opposite
  vendor="$(grep -m1 'vendor_id' /proc/cpuinfo | awk '{print $3}' || true)"
  case "$vendor" in
    GenuineIntel) ensure_package intel-microcode; opposite=amd64-microcode;;
    AuthenticAMD) ensure_package amd64-microcode; opposite=intel-microcode;;
    *) warn "Unknown CPU vendor '$vendor'. Skipping microcode package cleanup."; return 0;;
  esac
  if dpkg -s "$opposite" >/dev/null 2>&1; then warn "$opposite is installed but will NOT be auto-removed because apt may remove kernel meta-packages with it. Review manually after confirming apt remove simulation."; fi
}

configure_wireguard(){
  [[ "$ENABLE_WIREGUARD" != yes ]] && return 0
  info "Configuring WireGuard"
  ensure_package wireguard
  ensure_package wireguard-tools
  ensure_package qrencode
  run "mkdir -p /etc/wireguard"
  run "chmod 700 /etc/wireguard"
  if [[ "$WIREGUARD_MODE" == "install-only" ]]; then
    ok "WireGuard packages selected for install only"
    return 0
  fi
  local key_file pub_file conf_file private_key peer_block
  key_file="/etc/wireguard/${WIREGUARD_INTERFACE}.key"
  pub_file="/etc/wireguard/${WIREGUARD_INTERFACE}.pub"
  conf_file="/etc/wireguard/${WIREGUARD_INTERFACE}.conf"
  if $APPLY; then
    if [[ ! -f "$key_file" ]]; then
      umask 077
      wg genkey > "$key_file"
      wg pubkey < "$key_file" > "$pub_file"
      chmod 600 "$key_file" "$pub_file"
    else
      ok "WireGuard private key already exists: $key_file"
      [[ -f "$pub_file" ]] || wg pubkey < "$key_file" > "$pub_file"
    fi
    private_key="$(cat "$key_file")"
  else
    private_key="DRY_RUN_PRIVATE_KEY_NOT_GENERATED"
  fi
  peer_block=""
  if [[ -n "$WIREGUARD_PEER_PUBLIC_KEY" && -n "$WIREGUARD_PEER_ALLOWED_IPS" ]]; then
    peer_block="
[Peer]
PublicKey = $WIREGUARD_PEER_PUBLIC_KEY
AllowedIPs = $WIREGUARD_PEER_ALLOWED_IPS"
  fi
  write_if_changed "$conf_file" "[Interface]
Address = $WIREGUARD_ADDRESS
ListenPort = $WIREGUARD_PORT
PrivateKey = $private_key$peer_block"
  run "chmod 600 '$conf_file'"
  run "ufw allow ${WIREGUARD_PORT}/udp comment 'WireGuard ${WIREGUARD_INTERFACE}'"
  run "systemctl enable wg-quick@${WIREGUARD_INTERFACE}"
  run "systemctl restart wg-quick@${WIREGUARD_INTERFACE}"
  if $APPLY; then
    ok "WireGuard public key: $(cat "$pub_file")"
    ok "WireGuard config: $conf_file"
  else
    ok "Dry-run: would generate WireGuard keys and config at $conf_file"
  fi
}

create_verify_script(){
  cat > "$VERIFY_SCRIPT" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

echo "========================================="
echo " Ubuntu 22.04 Setup Verification"
echo "========================================="
check(){ local name="$1" cmd="$2"; echo; echo "---- $name ----"; bash -c "$cmd" || echo "FAILED: $name"; }

check "Ubuntu release" "lsb_release -a 2>/dev/null || cat /etc/os-release"
check "Release upgrade policy" "grep -E '^Prompt=' /etc/update-manager/release-upgrades || true"
check "Reboot required" "if [[ -f /var/run/reboot-required ]]; then cat /var/run/reboot-required; else echo 'No reboot-required flag present'; fi"
check "Unattended upgrades" "systemctl is-enabled unattended-upgrades 2>/dev/null || true; systemctl is-active unattended-upgrades 2>/dev/null || true; cat /etc/apt/apt.conf.d/20auto-upgrades 2>/dev/null || true"
check "Swap" "swapon --show && free -h && grep '/swapfile' /etc/fstab"
check "Sysctl memory tuning" "sysctl vm.swappiness vm.vfs_cache_pressure vm.dirty_ratio vm.dirty_background_ratio"
check "Sysctl file/network/kernel tuning" "sysctl fs.file-max fs.inotify.max_user_watches fs.inotify.max_user_instances net.core.somaxconn net.ipv4.tcp_max_syn_backlog net.core.default_qdisc net.ipv4.tcp_congestion_control kernel.panic"
check "Limits config file" "cat /etc/security/limits.d/99-custom-limits.conf"
check "PAM limits" "grep pam_limits.so /etc/pam.d/common-session /etc/pam.d/common-session-noninteractive"
check "Systemd limits" "cat /etc/systemd/system.conf.d/99-custom-limits.conf && systemctl show --property DefaultLimitNOFILE --property DefaultLimitNPROC"
check "Current shell limit" "ulimit -n && ulimit -u"
check "Timezone and time sync" "timedatectl"
check "Chrony service" "systemctl is-enabled chrony && systemctl is-active chrony && chronyc tracking && chronyc sources"
check "Old/conflicting time services" "systemctl is-active systemd-timesyncd || true; dpkg -s ntp >/dev/null 2>&1 && echo 'WARNING: ntp package still installed' || echo 'OK: ntp package removed'"
check "UFW firewall" "ufw status verbose"
check "Fail2Ban" "systemctl is-enabled fail2ban && systemctl is-active fail2ban && fail2ban-client status || true"
check "SSH config" "sshd -t && grep -E '^(PermitRootLogin|PasswordAuthentication|PubkeyAuthentication|KbdInteractiveAuthentication|ChallengeResponseAuthentication|UsePAM|MaxAuthTries|ClientAliveInterval|ClientAliveCountMax)' /etc/ssh/sshd_config"
check "fstrim timer" "systemctl is-enabled fstrim.timer && systemctl is-active fstrim.timer && systemctl list-timers fstrim.timer --no-pager"
check "CPU microcode packages" "dpkg-query -W -f='\\${binary:Package} \\${Version}\\n' intel-microcode amd64-microcode 2>/dev/null || true"
check "WireGuard packages" "dpkg-query -W -f='\\${binary:Package} \\${Version}\\n' wireguard wireguard-tools qrencode 2>/dev/null || true"
check "WireGuard interfaces" "wg show 2>/dev/null || echo 'No active WireGuard interface detected'"
check "Installed utility packages" "dpkg-query -W -f='\\${binary:Package} \\${Version}\\n' htop btop iotop iftop nvme-cli smartmontools curl wget unzip jq git net-tools dnsutils tmux rsync lsof fail2ban ufw unattended-upgrades needrestart chrony ntpstat logrotate 2>/dev/null || true"
check "Baseline summary" "cat /root/server-baseline-summary.txt 2>/dev/null || echo 'No summary file found'"
check "Saved configs" "ls -lah /root/system-setup-configs/ 2>/dev/null || echo 'No config folder found'"
check "Backup folders" "ls -lah /root/system-setup-backups/ 2>/dev/null || echo 'No backup folder found'"
check "Log folders" "ls -lah /root/system-setup-logs/ 2>/dev/null || echo 'No log folder found'"
echo; echo "========================================="; echo " Verification complete"; echo "========================================="
EOF
  chmod +x "$VERIFY_SCRIPT"
}

write_summary(){
  local ips reboot_status release_prompt wg_status
  ips="$(hostname -I 2>/dev/null | xargs || true)"
  reboot_status="$(if [[ -f /var/run/reboot-required ]]; then echo yes; else echo no; fi)"
  release_prompt="$(grep -E '^Prompt=' /etc/update-manager/release-upgrades 2>/dev/null || true)"
  wg_status="$(wg show 2>/dev/null || echo 'No active WireGuard interface detected')"
  cat > "$SUMMARY_FILE" <<EOF
Ubuntu Server Baseline Summary
==============================
Script: $SCRIPT_NAME
Version: $SCRIPT_VERSION
Run ID: $RUN_ID
Applied: $APPLY
Config Loaded: $CONFIG_LOADED
Config File: ${CONFIG_FILE:-$GENERATED_CONFIG_FILE}
Date UTC: $(date -u)
Hostname: $(hostname)
Server Role: ${SERVER_ROLE:-unknown}
Provider/Location: ${SERVER_LOCATION:-unknown}
Admin User: ${ADMIN_USER:-unknown}
Desired Swap Size: ${SWAP_SIZE:-unknown}
Limit Profile: ${LIMIT_PROFILE:-unknown}
nofile Limit: ${LIMIT_VALUE:-unknown}
nproc Limit: ${NPROC_VALUE:-unknown}
fs.file-max: ${FILE_MAX:-unknown}
Run System Updates: ${RUN_SYSTEM_UPDATES:-unknown}
Unattended Security Updates: ${ENABLE_UNATTENDED_SECURITY_UPDATES:-unknown}
Release Upgrade Policy: ${release_prompt:-unknown}
Reboot Required: $reboot_status
WireGuard Enabled: ${ENABLE_WIREGUARD:-unknown}
WireGuard Mode: ${WIREGUARD_MODE:-unknown}
WireGuard Interface: ${WIREGUARD_INTERFACE:-unknown}
WireGuard Port: ${WIREGUARD_PORT:-unknown}
IP Addresses: $ips

Swap:
$(swapon --show 2>/dev/null || true)

UFW:
$(ufw status verbose 2>/dev/null || true)

Chrony:
$(chronyc tracking 2>/dev/null || true)

Microcode Packages:
$(microcode_report)

WireGuard:
$wg_status

Logs: $LOG_DIR
Backups: $BACKUP_DIR
Saved Config: ${CONFIG_FILE:-$GENERATED_CONFIG_FILE}
Verify Script: $VERIFY_SCRIPT
EOF
}

# Start
echo "========================================="; echo " $SCRIPT_NAME v$SCRIPT_VERSION"; echo " Mode: $($APPLY && echo APPLY || echo DRY-RUN)"; echo "========================================="
if [[ -n "$CONFIG_FILE" ]]; then load_config "$CONFIG_FILE"; elif $APPLY; then load_latest_config_if_requested; fi
if ! $CONFIG_LOADED; then ! $APPLY && warn "Dry-run mode will NOT ask for hidden password entry. Password prompts only run with --apply."; collect_config; save_config; else show_config_summary; prompt_yes_no "Continue with this loaded configuration?" "Y" || fail "Aborted by user"; fi
validate_config; show_config_summary
[[ "$(hostname)" != "$SERVER_HOSTNAME" ]] && run "hostnamectl set-hostname '$SERVER_HOSTNAME'" || ok "Hostname already $SERVER_HOSTNAME"

run_system_updates

info "Installing baseline packages"
PACKAGES=(htop btop iotop iftop nvme-cli smartmontools curl wget unzip jq git net-tools dnsutils tmux rsync lsof fail2ban ufw unattended-upgrades needrestart chrony ntpstat logrotate sudo openssh-server)
for p in "${PACKAGES[@]}"; do ensure_package "$p"; done
dpkg -s ntp >/dev/null 2>&1 && run "apt remove -y ntp" || ok "ntp package not installed"

info "Configuring timezone"; [[ "$(timedatectl show -p Timezone --value || true)" != UTC ]] && run "timedatectl set-timezone UTC" || ok "Timezone already UTC"

info "Creating sudo admin user"
id "$ADMIN_USER" >/dev/null 2>&1 && ok "User $ADMIN_USER already exists" || run "adduser --disabled-password --gecos '' '$ADMIN_USER'"
run "usermod -aG sudo '$ADMIN_USER'"
ADMIN_HOME="/home/$ADMIN_USER"; ADMIN_SSH_DIR="$ADMIN_HOME/.ssh"; ADMIN_AUTH_KEYS="$ADMIN_SSH_DIR/authorized_keys"
run "mkdir -p '$ADMIN_SSH_DIR'"; run "touch '$ADMIN_AUTH_KEYS'"; run "chmod 700 '$ADMIN_SSH_DIR'"; run "chmod 600 '$ADMIN_AUTH_KEYS'"; run "chown -R '$ADMIN_USER:$ADMIN_USER' '$ADMIN_SSH_DIR'"
case "$SSH_KEY_OPTION" in
  1) [[ -z "$ADMIN_PUBLIC_KEY" ]] && fail "SSH_KEY_OPTION=1 requires ADMIN_PUBLIC_KEY"; grep -Fxq "$ADMIN_PUBLIC_KEY" "$ADMIN_AUTH_KEYS" 2>/dev/null && ok "SSH key already exists for $ADMIN_USER" || run "echo '$ADMIN_PUBLIC_KEY' >> '$ADMIN_AUTH_KEYS'";;
  2) [[ -f /root/.ssh/authorized_keys ]] || fail "/root/.ssh/authorized_keys not found. Use SSH_KEY_OPTION=1 or 3."; run "cat /root/.ssh/authorized_keys >> '$ADMIN_AUTH_KEYS'"; run "sort -u '$ADMIN_AUTH_KEYS' -o '$ADMIN_AUTH_KEYS'";;
  3) KEY_PATH="/root/${ADMIN_USER}_ed25519"; [[ -f "$KEY_PATH" ]] && ok "Generated key already exists at $KEY_PATH" || { run "ssh-keygen -t ed25519 -a 100 -f '$KEY_PATH' -N '' -C '${ADMIN_USER}@${SERVER_HOSTNAME}'"; run "cat '${KEY_PATH}.pub' >> '$ADMIN_AUTH_KEYS'"; }; warn "Save private key securely from: $KEY_PATH";;
  *) fail "Invalid SSH key option: $SSH_KEY_OPTION";;
esac
run "chown -R '$ADMIN_USER:$ADMIN_USER' '$ADMIN_SSH_DIR'"; run "chmod 700 '$ADMIN_SSH_DIR'"; run "chmod 600 '$ADMIN_AUTH_KEYS'"
$APPLY && [[ ! -s "$ADMIN_AUTH_KEYS" ]] && fail "$ADMIN_USER has no SSH authorized_keys. Refusing to disable root SSH."
[[ "$ALLOW_PASSWORDLESS_SUDO" == yes ]] && { run "echo '$ADMIN_USER ALL=(ALL) NOPASSWD:ALL' > '/etc/sudoers.d/90-$ADMIN_USER'"; run "chmod 440 '/etc/sudoers.d/90-$ADMIN_USER'"; } || ok "Normal sudo selected"
[[ "$SET_ADMIN_PASSWORD" == yes ]] && { ADMIN_LOCAL_PASSWORD_SELECTED=yes; password_prompt "$ADMIN_USER" "$ADMIN_USER"; } || { ADMIN_LOCAL_PASSWORD_SELECTED=no; warn "No local password selected for $ADMIN_USER"; }
$APPLY && visudo -cf /etc/sudoers

info "Root account security"; [[ "$SET_ROOT_PASSWORD" == yes ]] && { ROOT_PASSWORD_CHANGE_SELECTED=yes; password_prompt root root; } || ROOT_PASSWORD_CHANGE_SELECTED=no; [[ "$LOCK_ROOT_PASSWORD" == yes ]] && run "passwd -l root" || ok "Root password left enabled for console/recovery use"

info "Checking swap"
CURRENT_SWAP_SIZE=0
if swapon --show=NAME,SIZE --bytes --noheadings | awk '{print $1}' | grep -qx "$SWAP_FILE"; then CURRENT_SWAP_SIZE="$(swapon --show=NAME,SIZE --bytes --noheadings | awk -v s="$SWAP_FILE" '$1==s {print $2}')"; fi
if [[ "$CURRENT_SWAP_SIZE" == "$SWAP_SIZE_BYTES" ]] && grep -q "^$SWAP_FILE none swap sw 0 0" /etc/fstab; then ok "$SWAP_SIZE swap already active and persistent"; else change "Configuring $SWAP_SIZE swap"; backup_file /etc/fstab; run "swapoff '$SWAP_FILE' || true"; run "rm -f '$SWAP_FILE'"; run "sed -i '\|$SWAP_FILE|d' /etc/fstab"; run "fallocate -l '$SWAP_SIZE' '$SWAP_FILE'"; run "chmod 600 '$SWAP_FILE'"; run "mkswap '$SWAP_FILE'"; run "swapon '$SWAP_FILE'"; run "echo '$SWAP_FILE none swap sw 0 0' >> /etc/fstab"; fi

info "Applying sysctl tuning"
write_if_changed /etc/sysctl.d/99-custom-system-tuning.conf "vm.swappiness=10
vm.vfs_cache_pressure=50
vm.dirty_ratio=15
vm.dirty_background_ratio=5
fs.file-max=$FILE_MAX
fs.inotify.max_user_watches=1048576
fs.inotify.max_user_instances=8192
net.core.somaxconn=65535
net.ipv4.tcp_max_syn_backlog=8192
net.core.default_qdisc=fq
net.ipv4.tcp_congestion_control=bbr
kernel.panic=10"
run "sysctl --system"

info "Applying security and systemd limits"
write_if_changed /etc/security/limits.d/99-custom-limits.conf "* soft nofile $LIMIT_VALUE
* hard nofile $LIMIT_VALUE
* soft nproc $NPROC_VALUE
* hard nproc $NPROC_VALUE
root soft nofile $LIMIT_VALUE
root hard nofile $LIMIT_VALUE
root soft nproc $NPROC_VALUE
root hard nproc $NPROC_VALUE"
ensure_line /etc/pam.d/common-session "session required pam_limits.so"; ensure_line /etc/pam.d/common-session-noninteractive "session required pam_limits.so"
write_if_changed /etc/systemd/system.conf.d/99-custom-limits.conf "[Manager]
DefaultLimitNOFILE=$LIMIT_VALUE
DefaultLimitNPROC=$NPROC_VALUE"
run "systemctl daemon-reexec"

info "Configuring UFW firewall"; ufw status | grep -q "22/tcp" && ok "UFW already allows SSH port 22" || run "ufw allow 22/tcp comment 'SSH'"
IFS=',' read -ra TCP_PORTS <<< "$EXTRA_TCP_PORTS"; for port in "${TCP_PORTS[@]}"; do port="$(echo "$port" | xargs)"; [[ -n "$port" ]] && run "ufw allow ${port}/tcp"; done
IFS=',' read -ra UDP_PORTS <<< "$EXTRA_UDP_PORTS"; for port in "${UDP_PORTS[@]}"; do port="$(echo "$port" | xargs)"; [[ -n "$port" ]] && run "ufw allow ${port}/udp"; done
ufw status | grep -q "Status: active" && ok "UFW already active" || run "ufw --force enable"

info "Configuring Fail2Ban"; run "systemctl enable fail2ban"; systemctl is-active fail2ban >/dev/null 2>&1 && ok "fail2ban already active" || run "systemctl start fail2ban"

info "Configuring Chrony"
write_if_changed /etc/chrony/chrony.conf "pool 0.ca.pool.ntp.org iburst maxsources 4
pool 1.ca.pool.ntp.org iburst maxsources 4
pool 2.ca.pool.ntp.org iburst maxsources 4
pool 3.ca.pool.ntp.org iburst maxsources 4
pool 0.north-america.pool.ntp.org iburst maxsources 4
pool 1.north-america.pool.ntp.org iburst maxsources 4
pool 2.north-america.pool.ntp.org iburst maxsources 4
pool 3.north-america.pool.ntp.org iburst maxsources 4
pool ntp.ubuntu.com iburst maxsources 4
pool pool.ntp.org iburst maxsources 4
driftfile /var/lib/chrony/chrony.drift
makestep 1.0 3
rtcsync
logdir /var/log/chrony"
run "systemctl disable --now systemd-timesyncd || true"; run "systemctl enable chrony"; run "systemctl restart chrony"

info "Hardening SSH"; backup_file /etc/ssh/sshd_config
set_sshd_option PermitRootLogin no; set_sshd_option PasswordAuthentication no; set_sshd_option PubkeyAuthentication yes; set_sshd_option KbdInteractiveAuthentication no; set_sshd_option ChallengeResponseAuthentication no; set_sshd_option UsePAM yes; set_sshd_option MaxAuthTries 3; set_sshd_option ClientAliveInterval 300; set_sshd_option ClientAliveCountMax 2
$APPLY && sshd -t; [[ "$SSH_CHANGED" == true ]] && run "systemctl restart ssh"

info "Enabling SSD/NVMe trim timer"; systemctl is-enabled fstrim.timer >/dev/null 2>&1 || run "systemctl enable fstrim.timer"; systemctl is-active fstrim.timer >/dev/null 2>&1 || run "systemctl start fstrim.timer"
configure_microcode
configure_wireguard

info "Creating verification script"; if $APPLY; then create_verify_script; write_summary; else echo "Dry-run: would create $VERIFY_SCRIPT and $SUMMARY_FILE"; fi

echo; echo "========================================="; echo " FINAL STATUS"; echo "========================================="
swapon --show || true; free -h || true; sysctl vm.swappiness vm.vfs_cache_pressure fs.file-max net.ipv4.tcp_congestion_control kernel.panic || true; ufw status verbose || true; systemctl status fail2ban --no-pager || true; command -v chronyc >/dev/null 2>&1 && chronyc tracking || true; timedatectl || true; command -v wg >/dev/null 2>&1 && wg show || true; sshd -t && echo "SSHD config valid"; [[ -f /var/run/reboot-required ]] && cat /var/run/reboot-required || echo "No reboot-required flag present"
echo "Logs: $LOG_DIR"; echo "Backups: $BACKUP_DIR"; echo "Saved config: ${CONFIG_FILE:-$GENERATED_CONFIG_FILE}"; echo "Summary: $SUMMARY_FILE"; echo "Verify script: $VERIFY_SCRIPT"
echo; echo "IMPORTANT: Before closing your current SSH/session, open a NEW terminal and test:"; echo "ssh $ADMIN_USER@SERVER_IP"; echo "sudo whoami"; echo "Expected result: root"
prompt_yes_no "Reboot now?" "N" && run "reboot" || echo "Recommended: reboot after first successful apply, especially if kernel updates were installed."
